# Generated by Django 2.2.1 on 2019-08-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190807_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
