# Generated by Django 2.2.1 on 2019-08-07 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190807_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='image',
            new_name='imageName',
        ),
    ]
