# Generated by Django 2.2.1 on 2019-08-08 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190808_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brands', to='api.Supplier'),
        ),
    ]
