# Generated by Django 2.2.1 on 2019-08-19 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190818_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transactionId',
        ),
    ]
